apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-servicemonitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: flask-app
  endpoints:
  - port: 5000
    path: /metrics
    interval: 15s
